const route = {
  "route": [
    {
      "term_id": 1069,
      "name": "Barcelona",
      "slug": "barcelona",
      "term_group": 0,
      "term_taxonomy_id": 1069,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "41.390205",
      "longitude": "2.154007"
    },
    {
      "term_id": 1071,
      "name": "Andorra la Vella",
      "slug": "andorra-la-vella",
      "term_group": 0,
      "term_taxonomy_id": 1071,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "42.5063039",
      "longitude": "1.5196113"
    },
    {
      "term_id": 1057,
      "name": "Escaldes-Engordany",
      "slug": "escaldes-engordany",
      "term_group": 0,
      "term_taxonomy_id": 1057,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "42.51183",
      "longitude": "1.5365334"
    },
    {
      "term_id": 1067,
      "name": "Valencia",
      "slug": "valencia",
      "term_group": 0,
      "term_taxonomy_id": 1067,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "39.4695235",
      "longitude": "-0.3778851"
    },
    {
      "term_id": 1061,
      "name": "Palma",
      "slug": "palma",
      "term_group": 0,
      "term_taxonomy_id": 1061,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "39.570743",
      "longitude": "2.649115"
    },
    {
      "term_id": 1063,
      "name": "Madrid",
      "slug": "madrid",
      "term_group": 0,
      "term_taxonomy_id": 1063,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "40.4381311",
      "longitude": "-3.8196197"
    },
    {
      "term_id": 1065,
      "name": "Cordoba",
      "slug": "cordoba",
      "term_group": 0,
      "term_taxonomy_id": 1065,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "37.8916069",
      "longitude": "-4.8195047"
    },
    {
      "term_id": 1059,
      "name": "Seville",
      "slug": "seville",
      "term_group": 0,
      "term_taxonomy_id": 1059,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "37.3892874",
      "longitude": "-5.9897966"
    }
  ],
    "before": null,
    "after": [
    {
      "term_id": 1076,
      "name": "Albufeira",
      "slug": "albufeira",
      "term_group": 0,
      "term_taxonomy_id": 1076,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "37.1122023",
      "longitude": "-8.2530071"
    },
    {
      "term_id": 1082,
      "name": "Lisbon",
      "slug": "lisbon",
      "term_group": 0,
      "term_taxonomy_id": 1082,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "38.7436883",
      "longitude": "-9.1952226"
    },
    {
      "term_id": 1080,
      "name": "Leiria",
      "slug": "leiria",
      "term_group": 0,
      "term_taxonomy_id": 1080,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "39.7541222",
      "longitude": "-8.8409781"
    },
    {
      "term_id": 1078,
      "name": "Coimbra",
      "slug": "coimbra",
      "term_group": 0,
      "term_taxonomy_id": 1078,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "40.2288202",
      "longitude": "-8.4512937"
    },
    {
      "term_id": 1084,
      "name": "Porto",
      "slug": "porto",
      "term_group": 0,
      "term_taxonomy_id": 1084,
      "taxonomy": "post_tag",
      "description": "",
      "parent": 0,
      "count": 1,
      "filter": "raw",
      "latitude": "41.1622023",
      "longitude": "-8.656973"
    }
  ]
};

export default route;
